### ISSUE TITLE
Awesome bytes!

### ISSUE THREAD

**Issue by xplshn** [tincan-linux/tincan#1]
Hi! I'm here to suggest using more statically linked stuff, I've seen your other projects and I deeply appreciate what you're doing, truly amazing stuff, and I love the ascii decorations and plain text readmes. Anyways, straight to the point, have you considered using a statically linked binary manager? Or adding support for it in your package manager project? Its much simpler than handling dependencies or, god forbid, dynamically linked stuff.

We're working over at https://github.com/Azathothas/Toolpacks to automate the build of thousands of statically linked programs, adding GUI programs is also in the roadmap, as well as single-binary toolchains, thought it may be helpful since building packages for an independent distro is usually what kills them, it is difficult and it takes a lot of man power.

I'm very interested in your project, most of all because I want to use it as the base for mine as well, which will/is called Andes-Linux.

I feel like I'm spamming, but I hope it helps to let you know that there exists ways to use programs without polluting the system with complexity (I consider ld.so the modern villain of any Unix clone).

Thanks for reading, have a good day :)

**Comment by avs-origami** [comment]
Thanks for stopping by and for taking an interest in this project!

No, I have not considered statically linked binaries. While it seems interesting, from what I've read it feels like static linking can be a bit of a nightmare sometimes, and just doesn't fit with the goals for my project, which are to:

- Keep the base as slim as possible, both for simplicity, and also so that I can reasonably maintain everything
- Make it easy for users to understand and tinker with the system
- Keep everything easily extensible (e.g. so that someone could easily use this on another architecture)

and I just don't think static linking or the toolpacks project fit into this vision particularly well. And of course if static linking is something that you care about, or if you want to use the toolpacks project as a source of packages, then it shouldn't be too hard to create your own repositories for `arc` that do just that. But for the main project it simply doesn't fit with my goals and vision.

I appreciate the feedback and suggestions though. If you are interested in trying it out, I have created a semi-finished installation guide at https://tincan-linux.github.io/install/hard that walks through the process of building Tin Can Linux from the ground up. And feel free to leave any other feedback that you may have!

**Comment by xplshn** [comment]
Thanks for the link!
